// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ewma_statistic_C
NumericVector ewma_statistic_C(NumericVector x, IntegerVector t, double lambda, double x0);
RcppExport SEXP _qclc_ewma_statistic_C(SEXP xSEXP, SEXP tSEXP, SEXP lambdaSEXP, SEXP x0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    rcpp_result_gen = Rcpp::wrap(ewma_statistic_C(x, t, lambda, x0));
    return rcpp_result_gen;
END_RCPP
}
// ma_statistic_C
NumericVector ma_statistic_C(NumericVector x, IntegerVector t, int omega);
RcppExport SEXP _qclc_ma_statistic_C(SEXP xSEXP, SEXP tSEXP, SEXP omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type omega(omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(ma_statistic_C(x, t, omega));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qclc_ewma_statistic_C", (DL_FUNC) &_qclc_ewma_statistic_C, 4},
    {"_qclc_ma_statistic_C", (DL_FUNC) &_qclc_ma_statistic_C, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_qclc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
