# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ewma_statistic_C <- function(x, t, lambda, x0) {
    .Call(`_qclc_ewma_statistic_C`, x, t, lambda, x0)
}

ma_statistic_C <- function(x, t, omega) {
    .Call(`_qclc_ma_statistic_C`, x, t, omega)
}

